config/routes.rb
UserAccount::Application.routes.draw do

  resources :genres

  root :to => 'movies#index'

  get '/movies/filter/:scope' => 'movies#index', :as => 'filtered_movies'
  resources :movies do
    resources :reviews
    resources :likes
  end

  resources :users
  get '/signup' => 'users#new', :as => 'signup'

  resource :session
end

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2013
    <%= link_to 'AppFolio','http://www.appfolio.com' %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<h1>AppFolio Movies</h1>
<nav>
  <% if @current_user ||= find_current_user %>
    <%= link_to @current_user.name, @current_user %> |
    <%= link_to 'Sign Out', session_path, :method => :delete %>
  <% else %>
    <li><%= link_to 'Sign Up', signup_path %></li>
    <li><%= link_to 'Sign In', new_session_path %></li>
  <% end %>
</nav>

app/views/layouts/_sidebar.html.erb
<nav>
  <ul>
    <li>
      <%= link_to 'New User', signup_path %>
    </li>
    <li>
      <%= link_to 'All Users', users_path %>
    </li>
    <li>
      <%= link_to 'Released Movies', movies_path %>
    </li>
    <li>
      <%= link_to 'Flops Movies', filtered_movies_path(:flops) %>
    </li>
    <li>
      <%= link_to 'Hits Movies', filtered_movies_path(:hits) %>
    </li>
    <% if current_user_admin? %>
      <li>
        <%= link_to 'Add New Movie', new_movie_path %>
      </li>
    <% end %>
    <div style="margin-top: 1em">
      <%= content_for :side %>
    </div>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title %></title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<% unless flash.empty? %>
  <div class='flash'>
    <% if flash[:notice] %>
      <div class='notice'>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class='alert'>
        <%= flash[:alert] %>
      </div>
    <% end %>
  </div>
<% end %>

<%= yield %>
<%= render 'layouts/sidebar' %>
<%= render 'layouts/footer' %>
</body>
</html>